// Code generated by "stringer -type Complexity complexity.go"; DO NOT EDIT.

package messageformat

import "strconv"

const _Complexity_name = "NoComplexitySingleLiteralSingleRoadComplex"

var _Complexity_index = [...]uint8{0, 12, 25, 35, 42}

func (i Complexity) String() string {
	if i < 0 || i >= Complexity(len(_Complexity_index)-1) {
		return "Complexity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Complexity_name[_Complexity_index[i]:_Complexity_index[i+1]]
}
